### ISSUE TITLE
Department names look bad on role select menu

### ISSUE THREAD

**Issue by Lyroth001** [Prison-Station-14/prison-station-14#14]
## Description
Department names shown to players look bad, SPSecurity should probably not be that

**Reproduction**
Open server
hover over roles
:(

**Screenshots**

![image](https://github.com/user-attachments/assets/bd40245b-34c5-4625-b532-61ef6d6ee6e1)

**Comment by Truoizys** [comment]
that would be super useful, I should probably get out some design docs for how much I want the playtime to be but honestly just translating it all to the new roles would save me sm time.

**Comment by Truoizys** [comment]
closed because I'm a dumbass and fixed it ages ago
