### ISSUE TITLE
Role playtime restrictions not set up for SP14 roles

### ISSUE THREAD

**Issue by Truoizys** [Prison-Station-14/prison-station-14#6]
## Description

Role playtime restrictions point toward unused vanilla departments for SP14 job roles

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Lyroth001** [comment]
I can give this a look

**Comment by Truoizys** [comment]
that would be super useful, I should probably get out some design docs for how much I want the playtime to be but honestly just translating it all to the new roles would save me sm time.
