### ISSUE TITLE
Some sprite variations needed for PS14 custom roles

### ISSUE THREAD

**Issue by Truoizys** [Prison-Station-14/prison-station-14#7]
## Description

A lot of mapping sprites currently used don't properly reflect the department/role names used in PS14, replacements for sprites such as door colours and lockers designs are needed.
Will update with listed sprites as found.

**Screenshots**

**Comment by unajoy** [comment]
ohhhhhhhh i guess so truzeeoids :(

**Comment by rynkatze** [comment]
Done in clothing /spiriting PR
